version: 2.1

orbs:
  terraform: circleci/terraform@2.1.0

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          checkout: true
          context:
            - AWS_CONFIG
            - TERRAFORM_CONFIG